### PR TITLE
Support CharSequence for text instead of String

### PR DESCRIPTION
**Pull request by gkravas**
Added Spannable text to Main activity also

### CODE REVIEW

**Comment by ViHtarb** [comment]
@gkravas if you urgently need this feature, i can now publish the version 0.2.0

**Comment by gkravas** [comment]
Yes please @ViHtarb. That would be a huge help :)

**Comment by ViHtarb** [comment]
@gkravas if you do not mind, I would prefer to start to publish a snapshot version because i want to implement custom animations in 0.2.0 version. Ok?

**Comment by gkravas** [comment]
Sure no problem





On Thu, Sep 29, 2016 at 7:25 PM +0300, "Viнt@rь" <notifications@github.com> wrote:












@gkravas if you do not mind, I would prefer to start to publish a snapshot version because i want to implement custom animations in 0.2.0 version. Ok?

**Comment by gkravas** [comment]
@ViHtarb sure no problem

**Comment by ViHtarb** [comment]
@gkravas done

**Comment by gkravas** [comment]
@ViHtarb Thnx again :)

**Comment by gkravas** [comment]
@ViHtarb are you sure is released, because I can't fetch it for repo

**Comment by ViHtarb** [comment]
@gkravas it`s released in SNAPSHOTS repo [looks this](https://github.com/ViHtarb/Tooltip#snapshots)

**Pull request merged**
